language: cpp
compiler:
    - gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get -qq install libpocofoundation9-dbg libpoconet9-dbg libpocoutil9-dbg libpoco-dev libpocofoundation9 libpoconet9 libpocoutil9 libgdal1 libgdal1-dev cmake g++ build-essential libpq-dev discount python
branches:
    only:
        - master
script: cmake . && make
